-- [1] friend

DROP TABLE FRIEND
CASCADE CONSTRAINTS;

DROP SEQUENCE F_SEQ;

SELECT * FROM FRIEND;

CREATE TABLE FRIEND(
	F_SEQ NUMBER(1) PRIMARY KEY,
	M_ID VARCHAR2(20) NOT NULL,
	F_ID VARCHAR2(20) NOT NULL,
	F_ACCEPT NUMBER(1) NOT NULL,
	F_GROUP NUMBER(1) NOT NULL,
	F_BLOCK NUMBER(1) NOT NULL
);

CREATE SEQUENCE F_SEQ
START WITH 1 INCREMENT BY 1;

ALTER TABLE FRIEND 
ADD CONSTRAINT FK_FRIEND_M_ID FOREIGN KEY(M_ID)
REFERENCES MEMBER(M_ID);

ALTER TABLE FRIEND 
ADD CONSTRAINT FK_FRIEND_F_ID FOREIGN KEY(F_ID)
REFERENCES MEMBER(M_ID);





